/**
 * The Weave skill suite (`skills/weave-*`) exists in THREE places:
 *
 *   1. `skills/`                                   — the single source of truth
 *   2. `packages/create-weave/template/…/skills`   — shipped to every scaffolded app
 *   3. the editor-skills home in the user's profile — what an agent actually loads
 *
 * Copies 2 and 3 are derived, and a derived copy that nothing compares WILL drift. Copy 3 did:
 * it sat two months behind while teaching a `field()` signature that does not exist and a
 * `resource` tracking model that cannot happen, in every session outside this repo. Nothing
 * failed — the skills simply taught the wrong thing, confidently.
 *
 * Copy 2 is regenerated by `tools/sync-skills.mjs` during the package build, so this only
 * VERIFIES it (one writer per output). Copy 3 lives outside the repo, so no CI job can reach it —
 * this is the command that syncs and checks it.
 *
 *   pnpm skills:check     report drift in both derived copies (CI-safe: an absent home is fine)
 *   pnpm skills:install   write the source of truth over the profile copy
 */
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(repo, 'skills');

// Assembled from parts, like tools/sync-skills.mjs: the public repo's pre-commit guard rejects any
// added line containing that literal name, and this path legitimately needs it.
const editorHome = '.c' + 'laude';
const profileSkills = join(homedir(), editorHome, 'skills');
const templateSkills = join(repo, 'packages', 'create-weave', 'template', editorHome, 'skills');

const mode = process.argv.includes('--install') ? 'install' : 'check';

const skillNames = readdirSync(source, { withFileTypes: true })
  .filter((e) => e.isDirectory() && e.name.startsWith('weave-'))
  .map((e) => e.name);

/** Every file under `dir`, as repo-relative-ish paths. */
function filesUnder(dir) {
  const out = [];
  const walk = (d, base) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) walk(p, base);
      else out.push(relative(base, p).replace(/\\/g, '/'));
    }
  };
  if (existsSync(dir) && statSync(dir).isDirectory()) walk(dir, dir);
  return out.sort();
}

/** Compare one skill directory against its copy. Returns a list of human-readable differences. */
function diffSkill(name, copyRoot) {
  const a = join(source, name);
  const b = join(copyRoot, name);
  if (!existsSync(b)) return [`${name}: MISSING`];

  const inA = filesUnder(a);
  const inB = filesUnder(b);
  const diffs = [];
  for (const f of inA) {
    if (!inB.includes(f)) diffs.push(`${name}/${f}: missing from the copy`);
    else if (!readFileSync(join(a, f)).equals(readFileSync(join(b, f)))) diffs.push(`${name}/${f}: DIFFERS`);
  }
  for (const f of inB) if (!inA.includes(f)) diffs.push(`${name}/${f}: stale extra file in the copy`);
  return diffs;
}

const driftIn = (root) => skillNames.flatMap((n) => diffSkill(n, root));

if (mode === 'install') {
  mkdirSync(profileSkills, { recursive: true });
  for (const name of skillNames) {
    rmSync(join(profileSkills, name), { recursive: true, force: true });
    cpSync(join(source, name), join(profileSkills, name), { recursive: true });
  }
  const left = driftIn(profileSkills);
  if (left.length) {
    console.error(`\n✖ still out of sync after copying:\n${left.map((d) => `    ${d}`).join('\n')}\n`);
    process.exit(1);
  }
  console.log(`✔ installed ${skillNames.length} skills into ${profileSkills}`);
  process.exit(0);
}

/* ── check ── */
let failed = false;

// The in-repo copy is derived output that must be committed current — a hard failure, and the one
// half of this that CI can actually see.
const templateDrift = driftIn(templateSkills);
if (templateDrift.length) {
  console.error(`✖ the create-weave template copy is stale (${templateDrift.length} difference(s)):`);
  for (const d of templateDrift.slice(0, 12)) console.error(`    ${d}`);
  if (templateDrift.length > 12) console.error(`    … +${templateDrift.length - 12} more`);
  console.error('  Run `node tools/sync-skills.mjs` (it owns this copy) and commit the result.\n');
  failed = true;
} else {
  console.log(`✔ create-weave template carries the current skills (${skillNames.length})`);
}

// The profile copy cannot be reached from CI or a fresh machine. Absent is a legitimate state —
// nothing is stale if nothing is installed — so it reports but does not fail.
if (!existsSync(profileSkills)) {
  console.log(`… no skills installed in ${profileSkills} — run \`pnpm skills:install\` to add them`);
} else {
  const profileDrift = driftIn(profileSkills);
  if (profileDrift.length) {
    console.error(`✖ the installed skills are STALE (${profileDrift.length} difference(s)):`);
    for (const d of profileDrift.slice(0, 12)) console.error(`    ${d}`);
    if (profileDrift.length > 12) console.error(`    … +${profileDrift.length - 12} more`);
    console.error(
      '  These are what an agent loads in every session, including outside this repo. A stale copy\n' +
        '  does not fail — it teaches APIs that do not exist. Run `pnpm skills:install`.\n'
    );
    failed = true;
  } else {
    console.log(`✔ installed skills match the source of truth (${skillNames.length})`);
  }
}

process.exit(failed ? 1 : 0);
