/**
 * The Weave skill suite (`skills/weave-*`) exists in FOUR kinds of place:
 *
 *   1. `skills/`                                   — the single source of truth
 *   2. `packages/create-weave/template/…/skills`   — shipped to every scaffolded app
 *   3. the editor-skills home in the user's profile — what an agent loads everywhere
 *   4. zero or more CONSUMING PROJECTS that vendor the suite into their own editor-skills
 *      directory, to pin it per-project instead of relying on the profile copy
 *
 * Copies 2-4 are derived, and a derived copy that nothing compares WILL drift. Copy 3 did:
 * it sat two months behind while teaching a `field()` signature that does not exist and a
 * `resource` tracking model that cannot happen, in every session outside this repo. Nothing
 * failed — the skills simply taught the wrong thing, confidently.
 *
 * Copy 2 is regenerated by `tools/sync-skills.mjs` during the package build, so this only
 * VERIFIES it (one writer per output). Copies 3 and 4 live outside the repo, so no CI job can
 * reach them — this is the command that syncs and checks them.
 *
 * Copy 4 is opt-in: name the project ROOT (not its skills directory) via `--project=<path>`,
 * repeatable, or the WEAVE_SKILLS_PROJECTS env var as a comma-separated list. A configured
 * project whose directory is absent reports and passes, exactly like an uninstalled profile —
 * a path that has not been vendored yet is not the same thing as a stale one.
 *
 *   pnpm skills:check     report drift in every derived copy (CI-safe: absent copies are fine)
 *   pnpm skills:install   write the source of truth over the profile + configured projects
 */
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const repo = join(dirname(fileURLToPath(import.meta.url)), '..');
const source = join(repo, 'skills');

// Assembled from parts, like tools/sync-skills.mjs: the public repo's pre-commit guard rejects any
// added line containing that literal name, and this path legitimately needs it.
const editorHome = '.c' + 'laude';
const profileSkills = join(homedir(), editorHome, 'skills');
const templateSkills = join(repo, 'packages', 'create-weave', 'template', editorHome, 'skills');

const mode = process.argv.includes('--install') ? 'install' : 'check';

/**
 * Consuming projects that vendor the suite, as project ROOTS — from repeatable `--project=<path>`
 * flags and/or the WEAVE_SKILLS_PROJECTS env var (comma-separated). Taking the root rather than
 * the skills directory keeps the editor-home segment assembled in exactly one place, and matches
 * how a caller thinks about their checkout.
 */
const projectRoots = [
  ...process.argv.filter((a) => a.startsWith('--project=')).map((a) => a.slice('--project='.length)),
  ...(process.env.WEAVE_SKILLS_PROJECTS ?? '').split(','),
]
  .map((p) => p.trim())
  .filter(Boolean)
  .map((p) => resolve(p))
  .filter((p, i, all) => all.indexOf(p) === i);

/** Where a consuming project keeps its vendored copy. */
const projectSkills = (root) => join(root, editorHome, 'skills');

const skillNames = readdirSync(source, { withFileTypes: true })
  .filter((e) => e.isDirectory() && e.name.startsWith('weave-'))
  .map((e) => e.name);

/** Every file under `dir`, as repo-relative-ish paths. */
function filesUnder(dir) {
  const out = [];
  const walk = (d, base) => {
    for (const e of readdirSync(d, { withFileTypes: true })) {
      const p = join(d, e.name);
      if (e.isDirectory()) walk(p, base);
      else out.push(relative(base, p).replace(/\\/g, '/'));
    }
  };
  if (existsSync(dir) && statSync(dir).isDirectory()) walk(dir, dir);
  return out.sort();
}

/** Compare one skill directory against its copy. Returns a list of human-readable differences. */
function diffSkill(name, copyRoot) {
  const a = join(source, name);
  const b = join(copyRoot, name);
  if (!existsSync(b)) return [`${name}: MISSING`];

  const inA = filesUnder(a);
  const inB = filesUnder(b);
  const diffs = [];
  for (const f of inA) {
    if (!inB.includes(f)) diffs.push(`${name}/${f}: missing from the copy`);
    else if (!readFileSync(join(a, f)).equals(readFileSync(join(b, f)))) diffs.push(`${name}/${f}: DIFFERS`);
  }
  for (const f of inB) if (!inA.includes(f)) diffs.push(`${name}/${f}: stale extra file in the copy`);
  return diffs;
}

const driftIn = (root) => skillNames.flatMap((n) => diffSkill(n, root));

if (mode === 'install') {
  // The profile copy plus every configured project. A configured project is CREATED if absent —
  // asking for it to be installed is the instruction to put it there.
  const destinations = [profileSkills, ...projectRoots.map(projectSkills)];
  let installFailed = false;

  for (const dest of destinations) {
    mkdirSync(dest, { recursive: true });
    for (const name of skillNames) {
      rmSync(join(dest, name), { recursive: true, force: true });
      cpSync(join(source, name), join(dest, name), { recursive: true });
    }
    const left = driftIn(dest);
    if (left.length) {
      console.error(`\n✖ ${dest} is still out of sync after copying:\n${left.map((d) => `    ${d}`).join('\n')}\n`);
      installFailed = true;
    } else {
      console.log(`✔ installed ${skillNames.length} skills into ${dest}`);
    }
  }

  process.exit(installFailed ? 1 : 0);
}

/* ── check ── */
let failed = false;

// The in-repo copy is derived output that must be committed current — a hard failure, and the one
// half of this that CI can actually see.
const templateDrift = driftIn(templateSkills);
if (templateDrift.length) {
  console.error(`✖ the create-weave template copy is stale (${templateDrift.length} difference(s)):`);
  for (const d of templateDrift.slice(0, 12)) console.error(`    ${d}`);
  if (templateDrift.length > 12) console.error(`    … +${templateDrift.length - 12} more`);
  console.error('  Run `node tools/sync-skills.mjs` (it owns this copy) and commit the result.\n');
  failed = true;
} else {
  console.log(`✔ create-weave template carries the current skills (${skillNames.length})`);
}

// The profile copy cannot be reached from CI or a fresh machine. Absent is a legitimate state —
// nothing is stale if nothing is installed — so it reports but does not fail.
if (!existsSync(profileSkills)) {
  console.log(`… no skills installed in ${profileSkills} — run \`pnpm skills:install\` to add them`);
} else {
  const profileDrift = driftIn(profileSkills);
  if (profileDrift.length) {
    console.error(`✖ the installed skills are STALE (${profileDrift.length} difference(s)):`);
    for (const d of profileDrift.slice(0, 12)) console.error(`    ${d}`);
    if (profileDrift.length > 12) console.error(`    … +${profileDrift.length - 12} more`);
    console.error(
      '  These are what an agent loads in every session, including outside this repo. A stale copy\n' +
        '  does not fail — it teaches APIs that do not exist. Run `pnpm skills:install`.\n'
    );
    failed = true;
  } else {
    console.log(`✔ installed skills match the source of truth (${skillNames.length})`);
  }
}

// Configured consuming projects. Same rule as the profile: a copy that is not there yet is a
// legitimate state and reports without failing; a copy that IS there and disagrees is stale, and
// stale is the failure — it silently teaches the wrong API in that project's every session.
for (const root of projectRoots) {
  const dir = projectSkills(root);
  if (!existsSync(dir)) {
    console.log(`… no skills vendored in ${dir} — run \`pnpm skills:install\` to add them`);
    continue;
  }
  const drift = driftIn(dir);
  if (drift.length) {
    console.error(`✖ the skills vendored in ${dir} are STALE (${drift.length} difference(s)):`);
    for (const d of drift.slice(0, 12)) console.error(`    ${d}`);
    if (drift.length > 12) console.error(`    … +${drift.length - 12} more`);
    console.error('  Run `pnpm skills:install` with this project configured.\n');
    failed = true;
  } else {
    console.log(`✔ ${dir} carries the current skills (${skillNames.length})`);
  }
}

process.exit(failed ? 1 : 0);
